### ISSUE TITLE
when I reproduced, I found that the cells_in_initial_clustering.txt file could not be found, how can I get this file,sincere thanks!

### ISSUE THREAD

**Issue by Jiahe-Sun** [winstonbecker/scCRC_continuum#3]
Hello, when I reproduced, I found that the cells_in_initial_clustering.txt file could not be found, how can I get this file,
Looking forward to your reply,
sincere thanks!

![image](https://user-images.githubusercontent.com/69581197/186559694-c6053c7d-fefc-4d59-9545-8dfb86d26203.png)

**Comment by winstonbecker** [comment]
Hi @sunjiahe-hub,

The file can be found here: https://drive.google.com/drive/folders/1fPgiGtk-vtQuYOx43qVTmo_63-A2YvcC?usp=sharing

Let me know if you have any trouble accessing. 

Also put the final cells and cell types here if it is useful: https://drive.google.com/drive/folders/1zk8EINx25VFCl1mtIgcPTw6rBI5n1939?usp=sharing
