### ISSUE TITLE
Curious about setting of sample-specific  filterFrags cutoffs in initial clustering of scATAC

### ISSUE THREAD

**Issue by jasondanic** [winstonbecker/scCRC_continuum#4]
Hi,
I have read your work ["Single-cell analyses reveal a continuum of cell state and composition changes in the malignant transformation of polyps to colorectal cancer"](https://www.nature.com/articles/s41588-022-01088-x) and it is enlightening.

There is an execute_steps 1 in  scATAC_initial_clustering.R that divided each sample into 'inputFiles1p5K', 'inputFiles3K', 'inputFiles4K' and 'inputFiles5K'. In next step, you setted sample-specific filterFrags(minFrags) to do filtering based those groups.

In fact, I am wondeing how those groups were divided and how those sample-specific cutoffs were setted, since I am facing with the troublesome situation that highly variable sequencing depth between samples.

Any replies might help, thanks.

Jason

**Comment by winstonbecker** [comment]
Hi! For selecting the cutoff, we just manually inspected the TSS vs unique fragments plots for each sample and tried to choose a cutoff that would isolate a clear population of cells. You could alternatively come up with a programatic approach to do this. Here are a few examples:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/15204322/224215720-54eed361-6a98-4c15-b0cd-4eda47a07f8f.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/15204322/224215778-361a7273-461d-494a-941c-63caf1791b8d.png">
